// <auto-generated />
namespace Linkofy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ierg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ierg));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251710464_ierg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
