// <auto-generated />
namespace Linkofy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ballz2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ballz2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801051106176_ballz2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
